# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY pyproject.toml /app

# Install pipenv and dependencies
RUN pip install --upgrade pip \
    && pip install hatchling

# Copy the rest of the source code
COPY src /app/src

# Expose the port that the app runs on
EXPOSE 8000

# Set environment variables for runtime
ENV JIRA_URL=<YOUR_JIRA_URL>
ENV JIRA_USERNAME=<YOUR_JIRA_USERNAME>
ENV JIRA_API_TOKEN=<YOUR_JIRA_API_TOKEN>
ENV PROJECT_KEY=<YOUR_PROJECT_KEY>
ENV API_KEY=<YOUR_API_KEY>

# Command to run the server
CMD ["python", "src/mcp_jira/server.py"]
